### ISSUE TITLE
example on homepage not working 

### ISSUE THREAD

**Issue by jtoy** [kyledrake/sinatra-synchrony#17]
require 'sinatra'
require 'sinatra/synchrony'
require 'rest-client'
require 'faraday'
Faraday.default_adapter = :em_synchrony

get '/' do
  Faraday.get 'http://google.com'
end

results in:
/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/rack-fiber_pool-0.9.2/lib/rack/fiber_pool.rb in rescue in block in call  env['async.callback'].call @rescue_exception.call(env, e)

this is on ruby 1.9.3

**Comment by kyledrake** [comment]
Thanks for noting, looks like there's a bug with 1.9.3. I will take a look this week, but 1.9.2 works if you need a workaround.

**Comment by jtoy** [comment]
I was unable to post the whole stacktrace because its embedded in the html output. I'm looking forward to trying this out!

**Comment by w-A-L-L-e** [comment]
Ouch still no fix for 1.9.3? Got same error here trying out synchrony in a sinatra json app.
undefined method `call' for nil:NilClass
file: fiber_pool.rb location: rescue in block in call line: 24

**Comment by kyledrake** [comment]
I have no idea why this isn't working on 1.9.3. I might spend a little time on it this weekend, but I guess this is kindof the problem with EventMachine in general. It's possible that this was a bug on something else has been fixed, but I'm not really sure what I can do on my side to deal with this.

If anybody figures this out, please let us know.. better yet send a pull request!

**Comment by rdsoze** [comment]
Its working fine for me.
sinatra-synchrony - 0.3.2
faraday - 0.8.1
 Is requiring rest-client necessary in the example as we're already using faraday ?

**Comment by w-A-L-L-e** [comment]
@ rsdoze what version of ruby?
run a ruby --version...
With 1.9.3p194 it doesn't for me.
