### ISSUE TITLE
sinatra-synchrony doesn't work with ruby 2.2.0 and padrino 0.12.4

### ISSUE THREAD

**Issue by faustoct1** [kyledrake/sinatra-synchrony#36]
I'm trying to run padrino + synchrony but I got this error when load my index page

[2015-03-02 03:47:53] ERROR NoMethodError: undefined method `join' for #<String:0x007f802a2306e8>
    /Users/fausto/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in`rescue in call'
    /Users/fausto/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
    /Users/fausto/.rvm/gems/ruby-2.2.0/gems/sinatra-synchrony-0.4.1/lib/sinatra/synchrony.rb:24:in`block in handle_exception'
    /Users/fausto/.rvm/gems/ruby-2.2.0/gems/rack-fiber_pool-0.9.3/lib/rack/fiber_pool.rb:25:in `call'
    /Users/fausto/.rvm/gems/ruby-2.2.0/gems/rack-fiber_pool-0.9.3/lib/rack/fiber_pool.rb:25:in`rescue in block in call'
    /Users/fausto/.rvm/gems/ruby-2.2.0/gems/rack-fiber_pool-0.9.3/lib/rack/fiber_pool.rb:21:in `block in call'
    /Users/fausto/.rvm/gems/ruby-2.2.0/gems/rack-fiber_pool-0.9.3/lib/fiber_pool.rb:48:in`call'
    /Users/fausto/.rvm/gems/ruby-2.2.0/gems/rack-fiber_pool-0.9.3/lib/fiber_pool.rb:48:in `block (3 levels) in initialize'
    /Users/fausto/.rvm/gems/ruby-2.2.0/gems/rack-fiber_pool-0.9.3/lib/fiber_pool.rb:47:in`loop'
    /Users/fausto/.rvm/gems/ruby-2.2.0/gems/rack-fiber_pool-0.9.3/lib/fiber_pool.rb:47:in `block (2 levels) in initialize'

**Comment by kyledrake** [comment]
Synchrony is obsolete. Instead of using this, you should just use Padrino with something like Puma, which will be concurrent on non-blocking IO based on the thread model.

**Comment by faustoct1** [comment]
wow. thanks puma works like a charm
